name: Meltano Install CI

on:
  pull_request:
    branches:
      - latest

jobs:
  build:
    runs-on: meltano/meltano:v2.19.1-python3.8

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: CI Meltano Install
      run: |
        meltano install
