# name: Meltano Install CI

# on:
#   pull_request:
#     branches:
#       - latest

# jobs:
#   build:
#     runs-on: meltano/meltano:v2.19.1-python3.8

#     steps:
#     - name: Checkout Code
#       uses: actions/checkout@v2

#     - name: CI Meltano Install
#       run: |
#         meltano install

name: Meltano Install CI

on:
  pull_request:
    branches:
      - latest

jobs:
  meltano_ci:
    name: Meltano CI
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Pip Install Meltano
        run: pip install meltano==2.19.1
          
      - name: Meltano Install
        run: meltano install
        
      - name: Build and publish Docker image
        run: docker build -t meltano_test .
        
